// Single source of truth for every campaign level. Levels 1-5 and 39 are
// hand-tuned (the first playable slice); levels 6-18 and 20-38 are
// generated by proceduralLevel() with monotonically increasing difficulty
// across each biome's arc - real, distinct, playable tuning, just
// formulaic rather than 33 individually hand-authored entries.

// Narrative title per level, kept as a standalone id->name lookup (rather
// than threaded through every hand-authored/procedural entry above) so it
// applies uniformly to both without touching the difficulty-tuning code.
const LEVEL_NAMES = {
  1: 'Awakening',
  2: 'The Farmhouse',
  3: 'Barn of the Dead',
  4: 'Cornfield Run',
  5: 'Blood on the Irrigation Ditch',
  6: 'Broken Windmill',
  7: 'Hollow Road',
  8: 'Escape from Undead Hollow',
  9: 'Main Street Massacre',
  10: "Sheriff's Last Stand",
  11: 'Valencia Market',
  12: 'School Lockdown',
  13: 'Highway 314',
  14: 'Bridge to Albuquerque',
  15: 'South Valley',
  16: 'Downtown Collapse',
  17: 'Old Town Nightmare',
  18: 'Hospital Zero',
  19: 'Industrial District',
  20: 'Airport Evacuation',
  21: 'Rio Grande Crossing',
  22: 'City of the Dead',
  23: 'National Guard Outpost',
  24: 'Convoy Ambush',
  25: 'Kirtland Perimeter',
  26: 'Hangar 12',
  27: 'Underground Bunker',
  28: 'Black Site',
  29: 'Desert Training Grounds',
  30: 'Last Flight Out',
  31: 'White Sands Crossing',
  32: 'Missile Range',
  33: 'Ghost Base',
  34: 'Classified Facility',
  35: 'Into the Nevada Desert',
  36: 'Perimeter Breach',
  37: 'The Research Labs',
  38: 'Patient Zero',
  39: 'A Cure for Tomorrow',
};

function proceduralLevel(id, biomeId, indexWithinArc, arcLength) {
  const t = arcLength > 1 ? indexWithinArc / (arcLength - 1) : 0; // 0..1 progress through this biome's arc
  return {
    id,
    biomeId,
    waveCount: 3 + Math.round(t * 4),
    zombiesPerWaveBase: 6 + Math.round(t * 6),
    zombiesPerWaveGrowth: 2 + Math.round(t * 2),
    maxConcurrent: 18 + Math.round(t * 14),
    isBossLevel: false,
  };
}

export const LevelConfig = [
  // Level 1 - Farm
  { id: 1, biomeId: 'farm', waveCount: 3, zombiesPerWaveBase: 5, zombiesPerWaveGrowth: 2, maxConcurrent: 16, isBossLevel: false },
  // Level 2 - Desert
  { id: 2, biomeId: 'desert', waveCount: 4, zombiesPerWaveBase: 6, zombiesPerWaveGrowth: 2, maxConcurrent: 18, isBossLevel: false },
  // Levels 3-5 - City arc opening (hand-tuned)
  { id: 3, biomeId: 'city', waveCount: 4, zombiesPerWaveBase: 6, zombiesPerWaveGrowth: 2, maxConcurrent: 18, isBossLevel: false },
  { id: 4, biomeId: 'city', waveCount: 4, zombiesPerWaveBase: 7, zombiesPerWaveGrowth: 2, maxConcurrent: 20, isBossLevel: false },
  { id: 5, biomeId: 'city', waveCount: 5, zombiesPerWaveBase: 7, zombiesPerWaveGrowth: 3, maxConcurrent: 22, isBossLevel: false },
  // Levels 6-18 - City arc continuation (procedural)
  ...Array.from({ length: 13 }, (_, i) => proceduralLevel(i + 6, 'city', i + 3, 16)),
  // Level 19 - Subway (procedural)
  proceduralLevel(19, 'subway', 0, 1),
  // Levels 20-25 - Marine base (procedural)
  ...Array.from({ length: 6 }, (_, i) => proceduralLevel(i + 20, 'marine_base', i, 6)),
  // Levels 26-38 - Army base (procedural)
  ...Array.from({ length: 13 }, (_, i) => proceduralLevel(i + 26, 'army_base', i, 13)),
  // Level 39 - Area 51, The Fallen boss finale
  { id: 39, biomeId: 'area51', isBossLevel: true, bossType: 'the_fallen' },
].map((level) => ({ ...level, displayName: LEVEL_NAMES[level.id] }));

export const TOTAL_LEVELS = LevelConfig.length;

export function getLevelConfig(levelId) {
  const config = LevelConfig.find((l) => l.id === levelId);
  if (!config) throw new Error(`Unknown level: ${levelId}`);
  return config;
}
